language: node_js
node_js:
- 8
script: npm run lint && npm test && npm i && npm run build
deploy:
  provider: npm
  email: ackeedevelopment@gmail.com
  skip_cleanup: true
  api_key:
    secure: C79ymxQcC/Rl00NtJFy4fbumOwvu9Jtz+maTuFZ7M3q0qb0EIeXSA0ywIYu2IPM27LYRGPkW9ijmBYvQWDA2xmD9nlRqdldAex8NTYt0tro2lZWl+iRbE0yWoyfcCHqlS0yS9v+DC3m0/IqYB8AX7V7//L/dLo8csbjeCXnB+YSg/P0pVfxRaJAIscO79slJubEHewWdlA5jbwfRH/CqJ3sOGtDSwcScOqvFYCnqOd+nS4j0+o4nBprODp7jiyOE90iNb9pvPZJVbMJhh90cIXbWxdUdmNkeK65Ks3O5BMpx0pm0ngaFMO0eDolFcCkA3Ia79QFzZdYSkmdVixACQ8jbvJsYDc1oZNwLYbcGnLWwz3VRQMQ4L37XByBjI6m4oro6fP/r1XCu4/qYZQUi/3+Y57bpVMqScK5/0XoOOchTwCr3AkKXVP5EifX0zwEc4KIErJADvRAkdMQ+onuBXU1dTe2oNj9cV+9sP6H1UQrdQzkhn5ADpSp7ca97wIY5wBPqVSg5FVbfwyTXzsLuY+0gS+iGg65SO43EKP4DOh5/vwZ819ITMENxL/Neb5STC6stZiNQKGnMmnJLCw+f7OkHtsEj8CBAJlhL5fbQ7mmxIm4D2HviDX7xiMwj3Bci+Iz+N7QmHOXhSJJNxujlCUspdz1aU1lRMQZee9bloe4=
  on:
    tags: true
    repo: AckeeCZ/$NAME
